version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.5.0
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.8.0
    - 3.8.1
    - 3.9.0
    - 3.9.1
    - 4.0.0
  - dependency-name: setuptools
    versions:
    - 52.0.0
    - 53.1.0
    - 54.0.0
    - 54.1.0
    - 54.1.1
    - 54.1.2
    - 54.1.3
    - 54.2.0
    - 56.0.0
  - dependency-name: pytest
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: twine
    versions:
    - 3.4.0
    - 3.4.1
  - dependency-name: lbt-dragonfly
    versions:
    - 0.6.32
    - 0.6.34
    - 0.7.0
    - 0.7.1
    - 0.7.10
    - 0.7.11
    - 0.7.12
    - 0.7.13
    - 0.7.15
    - 0.7.17
    - 0.7.18
    - 0.7.19
    - 0.7.2
    - 0.7.20
    - 0.7.22
    - 0.7.23
    - 0.7.24
    - 0.7.27
    - 0.7.3
    - 0.7.6
    - 0.7.7
    - 0.7.8
    - 0.7.9
  - dependency-name: lbt-honeybee
    versions:
    - 0.2.317
    - 0.2.318
    - 0.2.319
    - 0.2.322
